### ISSUE TITLE
Fix broken fix #450 - Creating a serverless application using the AWS CDK

### ISSUE THREAD

**Issue by Hustenbonbon** [awsdocs/aws-cdk-guide#454]
As my comment in closed issue #450 stated, the fix from #451 is broken. 
I'm going to provide a hotfix in a minute as a PR.

**Comment by markusl** [comment]
Hi @Hustenbonbon. Please check the updated documentation at https://docs.aws.amazon.com/cdk/v2/guide/serverless_example.html and let us know if there are any other improvements needed. The examples are now using AWS JS SDK v3 and the latest version of AWS Lambda runtimes.

**Comment by Hustenbonbon** [comment]
Hi, thanks for reaching out. 
I currently get this error after the first part: 
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'widgets'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'widgets'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:997:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1032:21)",
        "    at async start (file:///var/runtime/index.mjs:1195:23)",
        "    at async file:///var/runtime/index.mjs:1201:1"
    ]
}
```
I couldn't find a fix immediately, do you want me to check further and make a PR?

**Comment by Hustenbonbon** [comment]
If you want to use `import` syntax in the lambda code, using lambda.NodeJsFunction might be the way to go instead of using lambda.Function
